version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
    ports:
      - "4173:80"
  management-microservices:
    build:
      context: ./management-microservices
    depends_on:
      - postgres
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: ssg
      TYPEORM_PASSWORD: ssg123
      TYPEORM_DATABASE: microgrpc
    volumes:
      - ./management-microservices:/usr/src/app
      - ./proto:/usr/src/app/proto
    ports:
      - "50051:50051"

  api-gateway:
    build:
      context: ./api-gateway
    depends_on:
      - management-microservices
    environment:
      GRPC_SERVER: management-microservices:50051
    volumes:
      - ./api-gateway:/usr/src/app
      - ./proto:/usr/src/app/proto
    ports:
      - "4000:4000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ssg
      POSTGRES_PASSWORD: ssg123
      POSTGRES_DB: microgrpc
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: